alter table cerberus.chat
    add column full_statistics_limit int not null default -1;

create table bot_settings
(
    id         varchar(255)             not null,
    state      varchar(255)             not null,
    updated_at timestamp with time zone not null,
    primary key (id)
);

create table message_statistics
(
    id              bigint generated by default as identity,
    chat_id         bigint not null,
    user_id         bigint not null,
    message_count   bigint not null,
    last_message_at timestamp with time zone,
    primary key (id),
    constraint uk_message_statistics_chat_user unique (chat_id, user_id)
);