create table if not exists cerberus.digest (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
                                             chat_id int NOT NULL,
                                             link_to_message varchar(300) NOT NULL,
                                             description varchar(300) NOT NULL,
                                             created_on timestamp NOT NULL,
                                             PRIMARY KEY(id),
                                             FOREIGN KEY(chat_id) REFERENCES chat(id)
);

alter table cerberus.chat add column digest_enabled boolean;

update cerberus.chat set digest_enabled = false;