create table if not exists cerberus.digest_pinned (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    chat_id int NOT NULL,
    pinned_message_id int NOT NULL,
    created_on timestamp NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (chat_id) references chat(id)
);