create table if not exists cerberus.rules (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
        ruleset varchar(3000),
        chat_id int NOT NULL,
        PRIMARY KEY(id)
);

alter table cerberus.chat add column rules_enabled boolean;

update cerberus.chat set rules_enabled = false;